# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: ltshum6-c@my.cityu.edu.hk
author_name: ltshum
has_binder: false
has_settings: true
kind: frontend
labextension_name: custom-slideshow
project_short_description: JupyterLab extension for animated slideshow.
python_name: custom_slideshow
repository: https://github.com/ltshum/fyp-custom-slideshow
test: true

